name: Renovate

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BITWARDEN_SECRETS_ACCESS_TOKEN }}
          secrets: |
            ${{ secrets.RENOVATE_TOKEN_UUID }} > RENOVATE_TOKEN

      - uses: renovatebot/github-action@v43.0.8
        with:
          token: ${{ env.RENOVATE_TOKEN }}
